import { beforeEach, describe, expect, it, vi } from 'vitest';
const mocks=vi.hoisted(()=>({intake:vi.fn(),project:vi.fn(),access:vi.fn(),create:vi.fn(),add:vi.fn(),rules:vi.fn(),assemblies:vi.fn(),engine:vi.fn()}));
vi.mock('./scope-db',()=>({createScopeRule:vi.fn(),getScopeRuleById:vi.fn(),getScopeRuleByCode:vi.fn(),listScopeRules:vi.fn(),loadActiveRulesForEngine:mocks.rules,updateScopeRule:vi.fn(),deactivateScopeRule:vi.fn(),reactivateScopeRule:vi.fn(),getScopeRuleStats:vi.fn(),createScopeDraft:mocks.create,getScopeDraftById:vi.fn(),listScopeDraftsForProject:vi.fn(),updateScopeDraftStatus:vi.fn(),addScopeDraftItems:mocks.add,getScopeDraftItems:vi.fn(),removeScopeDraftItem:vi.fn(),clearScopeDraftItems:vi.fn(),getScopeDraftWithItems:vi.fn(),seedScopeRules:vi.fn()}));
vi.mock('./intake-db',()=>({getIntakeFormById:mocks.intake}));vi.mock('./project-db',()=>({getProjectById:mocks.project}));vi.mock('./project-access',()=>({requireProjectAccessTrpc:mocks.access,requireEntityAccess:vi.fn(),getScopeDraftIdForItem:vi.fn()}));vi.mock('./assembly-db',()=>({listAssemblies:mocks.assemblies}));vi.mock('@shared/scope-engine',()=>({generateScopeDraft:mocks.engine,convertScopeToBundle:vi.fn(),validateIntakeForScope:vi.fn()}));
import {scopeRouter} from './scope-router';
const TENANT='b1700000-0000-4000-8000-000000000001';const PROJECT='b1700000-0000-4000-8000-000000000002';const INTAKE='b1700000-0000-4000-8000-000000000003';const ASM='b1700000-0000-4000-8000-000000000004';
const caller=(tenantId:string|null=TENANT)=>scopeRouter.createCaller({user:{id:TENANT,role:'admin'},tenantId}as any);
beforeEach(()=>{vi.resetAllMocks();mocks.intake.mockResolvedValue({id:INTAKE,projectId:PROJECT,tenantId:TENANT,serviceType:'repair'});mocks.project.mockResolvedValue({id:PROJECT,tenantId:TENANT,projectType:'repair'});mocks.rules.mockResolvedValue([]);mocks.assemblies.mockResolvedValue({items:[]});mocks.engine.mockReturnValue({confidenceScore:1,warnings:[],items:[{assemblyId:ASM,quantity:2,unit:'EA',reason:'Fixture',confidence:1,sortOrder:0}]});mocks.create.mockResolvedValue({id:INTAKE});});
describe('scope generation ownership',()=>{
 it('persists owning tenant and items in one atomic helper call',async()=>{await caller().generate({intakeFormId:INTAKE,projectId:PROJECT});expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({tenantId:TENANT,projectId:PROJECT,intakeFormId:INTAKE}),TENANT,[expect.objectContaining({assemblyId:ASM,quantity:'2'})]);expect(mocks.add).not.toHaveBeenCalled();});
 it.each(['other',null])('rejects intake tenant %s before engine or writes',async tenantId=>{mocks.intake.mockResolvedValue({id:INTAKE,projectId:PROJECT,tenantId});await expect(caller().generate({intakeFormId:INTAKE,projectId:PROJECT})).rejects.toMatchObject({code:'FORBIDDEN'});expect(mocks.engine).not.toHaveBeenCalled();expect(mocks.create).not.toHaveBeenCalled();});
 it('rejects an intake from another project in the same tenant',async()=>{mocks.intake.mockResolvedValue({id:INTAKE,projectId:INTAKE,tenantId:TENANT});await expect(caller().generate({intakeFormId:INTAKE,projectId:PROJECT})).rejects.toMatchObject({code:'BAD_REQUEST'});expect(mocks.rules).not.toHaveBeenCalled();});
 it('rejects missing caller tenant',async()=>{await expect(caller(null).generate({intakeFormId:INTAKE,projectId:PROJECT})).rejects.toMatchObject({code:'FORBIDDEN'});expect(mocks.intake).not.toHaveBeenCalled();});
 it('rejects stale project ownership even if access previously passed',async()=>{mocks.project.mockResolvedValue({id:PROJECT,tenantId:'other'});await expect(caller().generate({intakeFormId:INTAKE,projectId:PROJECT})).rejects.toMatchObject({code:'FORBIDDEN'});expect(mocks.rules).not.toHaveBeenCalled();});
 it('rejects a deleted project before reading catalog or creating a draft',async()=>{mocks.project.mockResolvedValue({id:PROJECT,tenantId:TENANT,deletedAt:new Date()});await expect(caller().generate({intakeFormId:INTAKE,projectId:PROJECT})).rejects.toMatchObject({code:'NOT_FOUND'});expect(mocks.rules).not.toHaveBeenCalled();expect(mocks.create).not.toHaveBeenCalled();});
 it('passes only owned assemblies and their rules to the engine across two tenants',async()=>{
   const foreign='b1700000-0000-4000-8000-000000000005';const legacy='b1700000-0000-4000-8000-000000000006';
   mocks.assemblies.mockResolvedValue({items:[{id:ASM,tenantId:TENANT,name:'Owned'},{id:foreign,tenantId:foreign,name:'Foreign'},{id:legacy,tenantId:null,name:'Unresolved'}]});
   mocks.rules.mockResolvedValue([{id:'owned-rule',assemblyId:ASM},{id:'foreign-rule',assemblyId:foreign},{id:'legacy-rule',assemblyId:legacy},{id:'missing-rule',assemblyId:'missing'}]);
   await caller().generate({intakeFormId:INTAKE,projectId:PROJECT});
   expect(mocks.engine).toHaveBeenCalledWith(expect.anything(),expect.anything(),[expect.objectContaining({id:'owned-rule',assemblyId:ASM})],[expect.objectContaining({id:ASM,name:'Owned'})]);
 });
});
